In [6]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np

In [10]:
data = load_iris()
X = data['data']
y = data['target']
print(X.shape)
y

(150, 4)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

4 features and 3 classes

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

Initializing parameters. \mathbf{W} &\in \mathbb{R}^{D \times C} \quad \text{(Weights)} \\
\mathbf{b} &\in \mathbb{R}^{C} \quad \text{(Bias vector)} \\

In [12]:
w = np.random.rand(4, 3)
b = np.random.rand(3)
w, b

(array([[0.44070342, 0.61086393, 0.05909535],
        [0.38421904, 0.93226569, 0.12532207],
        [0.02264705, 0.12391115, 0.17954915],
        [0.69839236, 0.27276352, 0.76657878]]),
 array([0.51468074, 0.45025529, 0.0227785 ]))

In [13]:
def softmax(Z):
    Z = np.exp(Z)
    sum = Z.sum()
    return Z / sum